### ISSUE TITLE
day05- Karin Vardy

### ISSUE THREAD

**Issue by karinvar** [szabgab/wis-python-course-2024-11#121]
https://github.com/karinvar/Python-assignments/tree/main/Day05
@liroh99

**Comment by liroh99** [comment]
Hi Karin, 
A few comments- 
First, your program does not show the combined statistics for handling multiple files. 
Second, you should run the program as such: python seq.py day05/a_seq.txt day05/b_seq.txt, instead of input you can use sys.argv to handle the filenames as we have studied in class. 
Third, the test you wrote is run through the main function, it is better to create a separate file for the testing and use pytest to validate it. 
Try to fix these issues before the deadline. 
Good luck!

**Comment by karinvar** [comment]
Hi Liron,
Thanks, I fixed it (I hope).
Karin
@liroh99

**Comment by liroh99** [comment]
Excellent 👍
