### ISSUE TITLE
Lihi Erez day05

### ISSUE THREAD

**Issue by Lihierez** [szabgab/wis-python-course-2024-11#125]
Day 05 assignment: https://github.com/Lihierez/python-assignments/tree/main/day05

@liroh99

**Comment by liroh99** [comment]
Hi Lihi, a few comments. 
Part of the assignment is to write a few tests that will validate your code, in class we learned how to use pytest to do so. 
Also, even though it's not wrong to call the function with the files you want, Gabor taught how the user can run the code and specify the files they want to give using sys.argv. This would be better because the user can input the files in the terminal without changing or adding to your code. 
Try to address these issues and resubmit it by tomorrow morning.

**Comment by Lihierez** [comment]
Hi Liron,
Thank you for the comments and the chance to fix :)
I update the function in the repository:
https://github.com/Lihierez/python-assignments/tree/main/day05
The file is "seq_stat.py". I added get files by arguments in the main function and another test function using pyset.

**Comment by Lihierez** [comment]
@liroh99

**Comment by liroh99** [comment]
Much better 💯 
For next time, I would suggest you put the test function in a separate file, it's easier to run the pytest command that way.
