### ISSUE TITLE
Day 2 Assignment

### ISSUE THREAD

**Issue by Stavoh** [szabgab/wis-python-course-2024-11#65]
Hi, although for some this course is easy, for me it's complicated. I piled few suggestions that I find helpful.

1. After struggling for 4 days with the assignment, I'm being asked by a tutor if I'm continuing the course or not.

- Please consider extending the deadlines to 8 days or more, so we have the opportunity to ask questions during the following lecture (or during the breaks).
- Also, no need to pressure us for not completing an assignment after 4 days as we have enough pressure regardless.

2. I'm a MacOS user and in many occasions, the lecture content does not fit the OS, i.e. git installation and MacOS-Terminal commands.

- If possible, please teach us how to overcome this. Where (google/youtube/chatgpt/etc) and what (search/prompts examples) to look for, in the next lecture.

3. I tried to follow the lecture recording but it's not very usable for an inexperienced individual like myself.

- If possible, please share the screen on Zoom in the next lectures so the resolution will be sufficient to understand what's displayed on the screen.
- Also, please disable the camera follow mode (where the camera moves and zooms) as the zoom sometimes results in some relevant information being omitted.

Finally, thanks for the informative lectures. I enjoy this course a lot despite the struggle.

**Comment by szabgab** [comment]
Thank you for your input and especially thank you for creating a public issue for this!
(and I know some might think I am being passive aggressive here, but no, I think it is much better you used the issue than a private email)

1. The TAs are trying to do their job in time and as several students have decided last week to leave the course they want to understand if you might be one of those.  If you need extension in the dead-line, feel free to ask your TA. I am sure she will allow you to do so. IF they contact you it is not intended to pressure you. It is intended to make sure you are fine.

2. I don't have MacOS so I can't show how it is done, but MacOS users (just as anyone else) will get hands-on help if they attend the presentation.  I am not sure I understand. Are you asking me to show a search for "how to install python on mac" ? Something else?

3. As I can see the video recorded the screen all the time. Via Zoom. The resolution has it issue but I think at one point I figured out how to make it better. It is not clear to me at what part of the video did you have problem with though. I also don't understand what's the problem of the camera following me. You have all the screen recordings fixed on the right hand side. Are we both talking about [this](https://weizmann.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=73bedf4b-44e0-47b0-802c-b22400ab2bc5) video? Could you mention some of the timestamps where you have issues with the recording?

**Comment by Stavoh** [comment]
1. Thanks for the clarification.

2. I understand that during and after the course, I'll face complications that I will need to somehow troubleshoot. If possible, please teach us how to find solutions for such complications. Sometimes a simple Google search isn't sufficient and I wonder if there are some tips and tricks in this regard.

3. The recording you've sent me is great. I was watching the one that was uploaded to the Moodle via Zoom.

Thanks for the descriptive response.

**Comment by HadarKlimovski** [comment]
Hi Stav,

Thank you for your comments. I wanted to clarify that you’re not expected to struggle with the assignment on your own. I sent you a reminder about the submission deadline because I want to ensure you have the opportunity to complete it and receive feedback.

Liron and I handle a high volume of student emails every day and make an effort to address everyone’s questions. I personally work on a Mac and would have been happy to help troubleshoot any issues you faced, even via Zoom if needed. Additionally, we have been flexible with extensions for students who requested them.

The reason I reached out to ask if you planned to continue the course was because I noticed you hadn’t submitted the assignment. This was simply to keep track of active students and make sure everyone who wants to continue has the support they need.

Remember, communication is key! If you need extra help, I am available after class or during breaks, and I’m more than willing to assist you.

Best regards,
Hadar

**Comment by szabgab** [comment]
@Stavoh 

2. OK, that I understand and it is usually part of the course
3. It took me a while to find the video link on Moodle, and it leads to the same video I linked above. Can you include the link to the video you found? Maybe with a screenshot where you found it?
