### ISSUE TITLE
Day 03 by Lihi Erez

### ISSUE THREAD

**Issue by Lihierez** [szabgab/wis-python-course-2024-11#76]
Link to python assignment/ Day03: https://github.com/Lihierez/python-assignments/tree/main/day03

**Comment by liroh99** [comment]
Overall nice job. 
In the code you wrote for qPCR, I would suggest being clearer on the input being given. I assume the data you gave is the Ct number of two different genes (one being the reference gene) for 3 different samples that come in triplicates- it would be helpful to write that down as a comment beforehand. The code can also be simplified, you can calculate the average of each three technical replicates, then calculate delta Ct for each sample -> you do not need to use nested loops. 
Otherwise, very good job, the code seems to work and it is not an easy trial :)
