### ISSUE TITLE
day04 Aishwarya Singh

### ISSUE THREAD

**Issue by Aish16032001** [szabgab/wis-python-course-2024-11#88]
Here is the link for day04 assignment - https://github.com/Aish16032001/Pythoncourse_assignments/tree/main/day04

@liroh99

**Comment by liroh99** [comment]
A small bug in your code, in the guessing game- your main function calls the game() function and saves it under new_game, but the loop looks at game and not new_game- causing a bug. If I input "x" after I guessed a number, it will not exit the game, but go straight to play_again. Tell me when you fixed this and I will close the issue. 
Otherwise good job :)

**Comment by Aish16032001** [comment]
@liroh99. I made the necessary changes. Have a look and let me know if anything else is missing
